# -*- coding: utf-8 -*-
"""Introduction to Numpy and Paper Testing Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MzCqgbe0Fn5GwyACuNj5_yYtlzrMqTC7
"""

pip install numpy pandas

import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
print(arr.shape)  # (3,)

arr2d = np.array([[1, 2], [3, 4]])
print(arr2d.shape)  # (2, 2)

arr + 5  # Adds 5 to each element
arr * 2  # Multiplies each element by 2

# Step 1: Create Sample Data (No file needed)
data = {
    'Grade': ['A', 'A', 'A', 'B', 'B', 'C', 'C', 'C'],
    'Tensile': [32, 29, 34, 26, 24, 20, 19, 18],
    'Tear': [13, 12, 14, 10, 9, 8, 8, 7],
    'Burst': [5.5, 5.2, 5.6, 4.9, 4.7, 4.0, 3.9, 3.7]
}

df = pd.DataFrame(data)
print("📄 Paper Testing Data:")
print(df)

# ✅ Step 2: Simple Summary Function
def print_summary(name, array):
    mean_val = np.mean(array)
    median_val = np.median(array)
    std_dev = np.std(array)

    print("----", name, "Statistics ----")
    print("Mean:", round(mean_val, 2))
    print("Median:", round(median_val, 2))
    print("Standard Deviation:", round(std_dev, 2))
    print("-----------------------------\n")

# ✅ Call the function for each column
print_summary("Tensile", df["Tensile"])
print_summary("Tear", df["Tear"])
print_summary("Burst", df["Burst"])